version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: kanban-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban_dev
    ports:
      - "5432:5432"